name: CI

on:
  push:
    branches:
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Restore packages
      run: dotnet restore
    - name: Build solution
      run: dotnet build
    - name: Pack NuGet package
      run: dotnet pack Formulator
    # - name: Push NuGet package
    #   run: dotnet nuget push Formulator/bin/release/Formulator.*.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
