name: CI

on:
  push:
    branches:
    - master
    - develop
    pull_request:
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Restore packages
      run: dotnet restore
    - name: Build solution
      run: dotnet build
